# Gitleaks configuration for dotfiles repository
title = ".config gitleaks config"

[extend]
# useDefault will extend the default gitleaks config built in to the binary
# the latest version is located at:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true
disableRules = ["sourcegraph-access-token"]

[[allowlists]]
paths = [
  '''.bun/install''',
  '''.cache''',
  '''.claude/ide''',
  '''.codex/auth.json''',
  '''.colima''',
  '''.config/colima''',
  '''.config/raycast/extensions''',
  '''.config/zsh/plugins''',
  '''.config/zsh/secrets.zsh''',
  '''.cursor/extensions''',
  '''.gem''',
  '''.local''',
  '''.mitmproxy''',
  '''.npm''',
  '''.nvm''',
  '''.ollama''',
  '''.rubies''',
  '''.rustup''',
  '''.vscode/extensions''',
  '''Applications''',
  '''Developer''',
  '''Documents''',
  '''Downloads''',
  '''Library''',
  '''Movies''',
  '''Music''',
  '''Pictures''',
  '''dotfiles''',
  '''esdata''',
  '''go''',
  '''p''',
  '''scratch''',
  '''src''',
]
description = "global allow list"

# Acceptable values for regexTarget are "match" and "line"
regexTarget = "match"
regexes = ['''YOUR_TOKEN''']
