return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "comment",
        "dockerfile",
        "editorconfig",
        "gotmpl",
        "html",
        "javascript",
        "json",
        "lua",
        "luadoc",
        "mermaid",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "ruby",
        "rust",
        "svelte",
        "tmux",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "zig",
        "zsh",
      },
    },
  },
}
