#!/usr/bin/env zsh
local name=$1

if [ -z "$name" ]; then
  echo "Usage: mkrepo <name> or mkrepo <org>/<name>"
  return 1
fi

local dir
if [[ "$name" == */* ]]; then
  dir="$HOME/src/$name"
else
  dir="$HOME/src/martinemde/$name"
fi
mkdir -p "$dir"
z "$dir"

if [ ! -d .jj ]; then
  jj init
fi
