#:schema https://mise.jdx.dev/schema/mise.json

[tools]
"aqua:jqlang/jq" = "latest"
"aqua:technicalpickles/envsense" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"cargo:starship-jj" = "latest"
bun = "latest"
go = "latest"
node = "latest"
python = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
